### ISSUE TITLE
Adding support for Web Clients like Zoom, Skype, Microsoft Teams, Webex, etc

### ISSUE THREAD

**Issue by yashtailor** [gisty-org/chrome-extension#4]
Currently the extension captures captions of google meet only, Support for other web clients is required. Understanding how the web clients generate captions and extracting the same by the extension while it being using in that domain. Currently major focus is on Zoom

**Comment by Kushal-Ajay-Shah** [comment]
- Platforms like Microsoft teams and Airmeet don't have support for live captions.
- Other platforms as a paid feature. 
- Webex already has notes making summary from captions as a paid feature.
- We made an effort to add extension to other platforms also but it was not useful due to the reasons above.

**Comment by yashtailor** [comment]
Closing due to lack of (free) services from the platforms.
